baseurl = "https://simplifymy.cloud"
DefaultContentLanguage = "en"
title = "Simplify My Cloud"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "UA-89675533-1"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Infrastructure Culture through automation and empathy"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  rss = true
  comments = false
  readingTime = false
  useHLJS = true
  socialShare = true
  commit = "https://github.com/SimplifyMyCloud/smc-website/tree/"
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "SimplifyMy.Cloud"
  website = "https://simplifymy.cloud"
  email = "info@simplifymy.cloud"
  #facebook = "username"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "SimplifyMyCloud"
  gitlab = "SimplifyMyCloud"
  #bitbucket = "username"
  twitter = "e30chris"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"

[[menu.main]]
    name = "Blog"
    url = "https://theargo.io"
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "infra_layers"
    name = "Infrastructure Layers"
    weight = 2

[[menu.main]]
    parent = "infra_layers"
    name = "App"
    url = "page/app-layer"
    weight = 1

[[menu.main]]
    parent = "infra_layers"
    name = "Service"
    url = "page/service-layer"
    weight = 2

[[menu.main]]
    parent = "infra_layers"
    name = "Foundation"
    url = "page/foundation-layer"
    weight = 3

[[menu.main]]
    name = "Consulting"
    url = "page/consulting"
    weight = 4
